spring.application.name=insurance Management System
spring.datasource.url=jdbc:postgresql://localhost:5432/InsuranceManagementSystem
spring.datasource.username=postgres
spring.datasource.password=Test@1234
spring.jpa.hibernate.ddl-auto=update
